apiVersion: v1
kind: Service
metadata:
  name: healthalliance-postgres-service
  labels:
    app: healthalliance-postgres
spec:
  type: ClusterIP
  selector:
    app: healthalliance-postgres
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
